language: cpp

cache: ccache

env:
  global:
    - secure: YdQjksdi5l3kyO5fvAUbKSM3ryFHkuxWmA+0+izFmyyMQ14JlEzMuGWZ3SkKq9fYW5tErOZYBdRrGo6esyLDlKFQvmJrMMUFq0zE8s9I6qpPIIzFlC8kZ/OgKe/gNHa5OZi4+lfBnxVWzxwS8zYs8pC1X7vj17FWQ7nfS1cxneWVrfNHHNJ2/70KQJ5QkRP2TtXsBCmjBQufVwmG9O09cuvwa+2spkZdRtQoMXJYWrc+buK/hjG/ARc4pU6UTjBe+/RS1L51TdzfhYQQppKyIOOVuPj21/hyR+2HGZSk25QUlv9lyAl/Opv9ME5Ue/jfJwhAoHvO7kk9+5X6qljkXb5doOvbrVUgGaXVfu87AaQw+PR32aaDrrihLXP/iyoGpUarvgZqa+VaCzaDrTsw/iMWzSnrYBPoMCFgoBYM6QyfE4GjJbvh+OYlqbCkDdIudXf7iY9Yi35Ye+3nfhsPMUhZQzZiXdIuZOoVtDNbk/7XtUYtqHX1fydowf89SBUxICAaoZ4KDmtkd8u4W/04SA0XBhdMuzhinlyw3S3agnHT9lKW1dWL4EvsZc2qCCEyzNH26SKwhj9EfwFmaCmKMDoVw7HkfiRg+Veje55xDjgcTdxmUOTNmWI1kpXQZSMbFXTYm3fpTW3DoOZ5CjWSoc3UPY8xgHSo28cDgFCOEzw=

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      install:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache
      - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      before_script:
      - export CMAKE=cmake
    - os: linux
      dist: trusty
      addons:
        apt:
         update: true
         sources:
           - ubuntu-toolchain-r-test
           - deadsnakes
         packages:
           - libcurl4-openssl-dev
           - python3.6-dev 
           - python3.6-venv
           - xorg-dev
           - libglu1-mesa-dev
           - libpulse-dev
           - libasound2-dev
           - pulseaudio
           - g++-7
           - gcc-7
           - binutils-2.26
           - libgtk-3-dev
      before_script:    
         - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
         - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
         - curl -Ls "https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download" -o gdrive
         - curl -Ls https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh -o cmake-3.10.3-Linux-x86_64.sh
         - bash cmake-3.10.3-Linux-x86_64.sh --skip-license
         - export CMAKE=$(pwd)/bin/cmake
         - export GDRIVE_EXEC_DIR=$(pwd)
         - export PATH=/usr/lib/binutils-2.26/bin:${PATH}
         - ld -v
      deploy:
        provider: script
        script: bash $TRAVIS_BUILD_DIR/deploy.sh
        skip_cleanup: true
        on:
          repo: EKA2L1/EKA2L1
          all_branches: true

script:
  - mkdir build
  - cd build
  - ${CMAKE} -DCMAKE_BUILD_TYPE=Release ..
  - make -j4
  - if ![ "$TRAVIS_OS_NAME" = "osx" ]; then make CTEST_OUTPUT_ON_FAILURE=1 test; fi
  - cd ..
