platform:
  - x64

environment:
  PYTHON: "C:\\Python36-x64"
  VCPKG_DEFAULT_TRIPLET: x64-windows
  
image:
  Visual Studio 2017

install:
  - ps: |
      $env:PATH = "$env:PYTHON;$env:PYTHON\Scripts\;$env:PATH"
  - python --version
  - cd c:\projects\eka2l1-mjiuq
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - cd ..

build_script:
  - appveyor AddMessage -Cagetory Information "Building EKA2L1 Core..."
  - msbuild build\EKA2L1.sln /target:console /maxcpucount:4 /p:Configuration=Release /p:Platform=x64
  - 7z a -m0=LZMA2 -mx9 EKA2L1.7z .\build\bin\Release\*
  - appveyor AddMessage -Category Information "Done." 

artifacts:
  - path: EKA2L1.7z
    name: EKA2L1
