trigger:
- master

jobs:
- job: Win32MSVC2017Build
  pool:     
    vmImage: 'vs2017-win2016'
  steps:
  - script: git submodule update --init --recursive
    displayName: Update submodules
  - script: mkdir build
    displayName: Make build directory
  - task: CMake@1
    inputs: 
      workingDirectory: 'build'
      cmakeArgs: '-G "Visual Studio 15 2017 Win64" ..'
  - task: MSBuild@1
    inputs:
      solution: 'build/ALL_BUILD.vcxproj'
      configuration: 'Release'
      maximumCpuCount: true
  - script: ekatests
    workingDirectory: 'build/src/tests/Release'
    displayName: Run tests

- job: LinuxGCC8Build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: git submodule update --init --recursive
    displayName: Update submodules
  - script: sudo apt-get install xorg-dev libglu1-mesa-dev
    displayName: Install MESA and X11 dependencies
  - script: |
      sudo apt-get install g++-8 gcc-8 libgtk-3-dev
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
    displayName: Setup GCC 8
  - script: mkdir build
    displayName: Make build directory
  - task: CMake@1
    inputs: 
      workingDirectory: 'build'
      cmakeArgs: '-DCMAKE_BUILD_TYPE=Release ..'
  - script: make -j4
    workingDirectory: 'build'
    displayName: Build EKA2L1
  - script: make CTEST_OUTPUT_ON_FAILURE=1 test
    workingDirectory: 'build'
    displayName: Run tests
